FROM python:3.9-slim

WORKDIR /app

# Copy the requirements.txt file and install dependencies
COPY requirements.txt requirements.txt
RUN pip install --no-cache-dir -r requirements.txt

# Copy the app.py file into the container
COPY app.py app.py

# Expose the port that Streamlit listens to
EXPOSE 8501

# Set environment variables
ENV LC_ALL=C.UTF-8
ENV LANG=C.UTF-8

# Run the Streamlit app
CMD ["streamlit", "run", "--server.enableCORS", "false", "app.py"]
